name: Caller Workflow

on:
  push:
    branches: [ main ]

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/reusable-build.yml@main
    with:
      version: '1.2.3'
    secrets:
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}